version: '2'
services:

  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker_compose/node/development/Dockerfile
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  django:
    container_name: django_server
    build:
      context: .
      dockerfile: ./docker_compose/django/development/Dockerfile
    command: /start.sh
    depends_on:
      - node
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"